package com.flywet.platform.bi.cust.p002.db;

public class CYDatabaseRepositoryBase {

	public static final String TABLE_BIHR_D_EMPLOYEE_AFFAIR = "BIHR_D_EMPLOYEE_AFFAIR";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ID_EMPLOYEE = "ID_EMPLOYEE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMP_NUM = "EMP_NUM";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_OLD_EMP_NUM = "OLD_EMP_NUM";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_NAME = "NAME";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_SEX = "SEX";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_JOB_CODE = "JOB_CODE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_POSITION = "POSITION";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ID_DEP = "ID_DEP";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_JOB1 = "JOB1";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DIRECT_MANAGER_NUM_1 = "DIRECT_MANAGER_NUM_1";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_JOB2 = "JOB2";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DIRECT_MANAGER_NUM_2 = "DIRECT_MANAGER_NUM_2";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ID_STATION = "ID_STATION";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ENTRY_DATE = "ENTRY_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_PERIOD_END_DATE = "PERIOD_END_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_CONTRACT_EXPIRY_DATE = "CONTRACT_EXPIRY_DATE";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ON_JOB_FLAG = "ON_JOB_FLAG";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DEPARTURE_DATE = "DEPARTURE_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DEPARTURE_CATEGORY_1 = "DEPARTURE_CATEGORY_1";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DEPARTURE_CATEGORY_2 = "DEPARTURE_CATEGORY_2";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_PAYMENT = "PAYMENT";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DEPARTURE_REASON_1 = "DEPARTURE_REASON_1";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DEPARTURE_REASON_2 = "DEPARTURE_REASON_2";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DEPARTURE_TARGET = "DEPARTURE_TARGET";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_PAY_RISE = "PAY_RISE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_JOB_CHANGEE = "JOB_CHANGE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_COMPLETED_DATE = "COMPLETED_DATE";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_INTERNSHIP_START_DATE = "INTERNSHIP_START_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_INTERNSHIP_END_DATE = "INTERNSHIP_END_DATE";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMAIL = "EMAIL";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_PHONE_NUM = "PHONE_NUM";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ID_NUM = "ID_NUM";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_BIRTHDAY = "BIRTHDAY";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_NATIVE_PLACE = "NATIVE_PLACE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_DOMICILE_PLACE = "DOMICILE_PLACE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_NATIONAL = "NATIONAL";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_POLITICAL_LANDSCAPE = "POLITICAL_LANDSCAPE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_GRADUATED_SCHOOL = "GRADUATED_SCHOOL";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_ADMISSION_DATE = "ADMISSION_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_GRADUATION_DATE = "GRADUATION_DATE";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_MAJAR = "MAJAR";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EDUCATION_BACKGROUND = "EDUCATION_BACKGROUND";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_IDS_LANGUAGE_AND_LEVEL = "IDS_LANGUAGE_AND_LEVEL";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_MARITAL_STATUS_FLAG = "MARITAL_STATUS_FLAG";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_START_WORK_DATE = "START_WORK_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_LAST_COMPANY = "LAST_COMPANY";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMERGENCY_CONTACT_PERSON = "EMERGENCY_CONTACT_PERSON";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_CONTACT = "CONTACT";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_RELATION_TO = "RELATION_TO";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_PRIVATE_EMAIL = "PRIVATE_EMAIL";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_WORKPLACE = "WORKPLACE";

	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMP_AFFAIR_TYPE = "EMP_AFFAIR_TYPE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMP_AFFAIR_DATE = "EMP_AFFAIR_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMP_AFFAIR_TIME = "EMP_AFFAIR_TIME";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMP_AFFAIR_END_DATE = "EMP_AFFAIR_END_DATE";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_EMP_AFFAIR_END_TIME = "EMP_AFFAIR_END_TIME";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_LASTEST_FLAG = "LASTEST_FLAG";
	public static final String FIELD_BIHR_D_EMPLOYEE_AFFAIR_BATCH_KEY = "BATCH_KEY";

	public static final String TABLE_BIHR_D_DEPARTMENT = "BIHR_D_DEPARTMENT";
	public static final String FIELD_BIHR_D_DEPARTMENT_ID_DEPARTMENT = "ID_DEPARTMENT";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEPARTMENT_FLAG = "DEPARTMENT_FLAG";
	public static final String FIELD_BIHR_D_DEPARTMENT_COMPANY = "COMPANY";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP0 = "DEP0";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP1 = "DEP1";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP2 = "DEP2";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP3 = "DEP3";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP4 = "DEP4";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP5 = "DEP5";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP6 = "DEP6";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP7 = "DEP7";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_SMALL = "DEP_SMALL";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_AFFAIR_TYPE = "DEP_AFFAIR_TYPE";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_AFFAIR_DESC = "DEP_AFFAIR_DESC";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_AFFAIR_DATE = "DEP_AFFAIR_DATE";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_AFFAIR_TIME = "DEP_AFFAIR_TIME";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_AFFAIR_END_DATE = "DEP_AFFAIR_END_DATE";
	public static final String FIELD_BIHR_D_DEPARTMENT_DEP_AFFAIR_END_TIME = "DEP_AFFAIR_END_TIME";
	public static final String FIELD_BIHR_D_DEPARTMENT_VALID_DEP_FLAG = "VALID_DEP_FLAG";
	public static final String FIELD_BIHR_D_DEPARTMENT_BATCH_KEY = "BATCH_KEY";
}
