//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SWListPropertyEditor.java
//  @ Date : 2013/6/19
//  @ Author : 
//
//



package uap.ui.bq.chart.editor;


public interface SWListPropertyEditor {
}
