package uap.vo.bq.chart.model;

public interface IChartJavaScript {
	public String getChartCaption() ;
	public void setChartCaption(String chartCaption) ;
	public String getChartSubCaption();
	public void setChartSubCaption(String chartSubCaption) ;
	public String getChartBgColor() ;
	public void setChartBgColor(String chartBgColor);
	public int getChartBgAlpha() ;
	public void setChartBgAlpha(int chartBgAlpha) ;
	public String getChartBorderColor() ;
	public void setChartBorderColor(String chartBorderColor) ;
	public int getChartBorderWidth() ;
	public void setChartBorderWidth(int chartBorderWidth);
	public int getChartBorderAlpha();
	public void setChartBorderAlpha(int chartBorderAlpha);
	public String getCanvasBgColor();
	public void setCanvasBgColor(String canvasBgColor);
	public int getCanvasBgAlpha();
	public void setCanvasBgAlpha(int canvasBgAlpha);
	public String getCanvasBorderColor();
	public void setCanvasBorderColor(String canvasBorderColor);
	public int getCanvasBorderWidth() ;
	public void setCanvasBorderWidth(int canvasBorderWidth) ;
	public int getCanvasBorderAlpha();
	public void setCanvasBorderAlpha(int canvasBorderAlpha);
	public boolean isShowLegend();
	public void setShowLegend(boolean showLegend);
	public String getLegendPosition();
	public void setLegendPosition(String legendPosition);
	public boolean isInteractiveLegend();
	public void setInteractiveLegend(boolean interactiveLegend);
	public boolean isShowHGridLine() ;
	public void setHGridLineNums(int showGridLine);
	public int getHGridLineNums();
	public boolean isDashedHGridLine();
	public void setDashedHGridLine(boolean dashedGridLine);
	public boolean isShowVGridLine() ;
	public void setVGridLineNums(int showGridLine);
	public int getVGridLineNums();
	public boolean isDashedVGridLine();
	public void setDashedVGridLine(boolean dashedGridLine);
}
